[package]
name = "server"
version = "0.1.0"
authors = ["WisartArfun <daro.daro15@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.7"
actix-http = "0.2.9"
mime = "0.3.13"
actix-web-actors = "1.0.2"
tungstenite = "0.9.1"