[package]
name = "Server"
version = "0.1.0"
authors = ["WisartArfun <daro.daro15@gmail.com>"]
edition = "2018"

[dependencies]
# ws = "0.9.0"
# rand = "*"
# actix = "0.7"
actix-web = "1.0.0"
actix-http = "*"
mime = "*"