refresh_rate: 30 seconds
appenders:
  stdout_detailed:
    kind: console
    encoder:
      pattern: "{f}{n}{M} - l: {L}{n}{d(%Y-%m-%d %H:%M:%S %Z)(utc)} [{h({l})}] - {m}{n}"
  stdout:
    kind: console
    encoder:
      pattern: "{d(%H:%M:%S %Z)(utc)} [{h({l})}] - {m}{n}"
  file:
    kind: file
    path: "logs/log.log"
    encoder:
      pattern: "{f}{n}{M} - l: {L}{n}{d(%Y-%m-%d %H:%M:%S %Z)(utc)} [{h({l})}] - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - file
loggers:
  app::backend::db:
    level: debug
  app::requests:
    level: debug
    appenders:
      - file
    additive: false